const samples = {
  translate: [
    { label: 'Legal Contract Clause', data: { text: 'The parties hereby agree that any disputes arising from or related to this agreement shall be resolved through binding arbitration in accordance with the rules of the International Chamber of Commerce. The arbitration shall take place in Geneva, Switzerland.', sourceLanguage: 'English', targetLanguage: 'German', tone: 'formal', domain: 'legal' } },
    { label: 'Medical Report', data: { text: 'The patient presented with acute myocardial infarction and was immediately administered aspirin and nitroglycerin. An emergency percutaneous coronary intervention was performed successfully. Post-procedure echocardiography revealed an ejection fraction of 45%.', sourceLanguage: 'English', targetLanguage: 'Spanish', tone: 'technical', domain: 'medical' } },
    { label: 'Marketing Copy', data: { text: 'Discover the future of skincare with our revolutionary AI-powered beauty serum. Clinically proven to reduce fine lines by 47% in just 4 weeks. Join over 2 million satisfied customers worldwide. Limited time offer: Buy 2, Get 1 Free!', sourceLanguage: 'English', targetLanguage: 'Japanese', tone: 'persuasive', domain: 'marketing' } },
  ],
  localize: [
    { label: 'E-commerce Product Page', data: { text: 'Free shipping on orders over $50! Our Black Friday sale starts November 24th. Use promo code SAVE20 for an extra 20% off. Items typically arrive within 3-5 business days. Prices shown in USD.', sourceLocale: 'en-US', targetLocale: 'ja-JP', contentType: 'e-commerce', industry: 'retail' } },
    { label: 'Restaurant Menu', data: { text: 'Our signature 12oz Angus beef burger, served with hand-cut fries and a side of ranch dressing. Pairs perfectly with our craft IPA. Allergens: gluten, dairy. Calories: 1,250 kcal.', sourceLocale: 'en-US', targetLocale: 'de-DE', contentType: 'food service', industry: 'hospitality' } },
    { label: 'Tech Product Launch', data: { text: 'Introducing the all-new SmartHome Hub 3.0 - now with Matter support and Thread connectivity. Control your entire smart home with Alexa, Google Assistant, or Siri. Starting at $129.99. Available at Best Buy and Amazon.', sourceLocale: 'en-US', targetLocale: 'zh-CN', contentType: 'product launch', industry: 'technology' } },
  ],
  grammar: [
    { label: 'Business Email (Errors)', data: { text: 'Dear Mr. Johnson, I wanted to followed up on our converstion from last weak. Me and my team has prepared the proposal your requested. Their are several key points we would like to dicuss at you\'re earliest convienence. Please let us no if Thursday works for a meeting. We look foreward to hearing from you. Best regards', language: 'English', styleGuide: 'Business Professional' } },
    { label: 'Academic Paper (Errors)', data: { text: 'The reserchers conducted a comperhensive analisis of the data, which revealled significant corelations between the independant and dependant variables. Alot of the participants shown improvement, however the control group did not showed any statistically signficant changes.', language: 'English', styleGuide: 'APA Academic' } },
    { label: 'French Marketing Copy', data: { text: 'Notre nouvelle collection est arrivé! Découvrez les derniere tendances de la mode printemp-été. Chaque pièce à été soigneusement séléctionné par nos expert en style. Profitez de la livraison gratuit sur tout les commandes.', language: 'French', styleGuide: 'Marketing' } },
  ],
  terminology: [
    { label: 'Cloud Computing Article', data: { text: 'The enterprise deployed a multi-cloud strategy using containerized microservices on Kubernetes clusters. The CI/CD pipeline integrates with the service mesh for canary deployments. Load balancing is handled by an API gateway with rate limiting and circuit breaker patterns.', domain: 'cloud computing', sourceLanguage: 'English', targetLanguage: 'Japanese' } },
    { label: 'Medical Research Paper', data: { text: 'Immunotherapy using checkpoint inhibitors has shown remarkable efficacy in treating non-small cell lung cancer. The PD-L1 expression levels were measured using immunohistochemistry. Patients receiving combination therapy with anti-PD-1 and anti-CTLA-4 antibodies demonstrated superior progression-free survival.', domain: 'oncology', sourceLanguage: 'English', targetLanguage: 'German' } },
    { label: 'Financial Regulations', data: { text: 'Basel III requires banks to maintain a minimum Common Equity Tier 1 ratio of 4.5% and a total capital adequacy ratio of 8%. The liquidity coverage ratio ensures sufficient high-quality liquid assets to cover net cash outflows over a 30-day stress scenario.', domain: 'finance', sourceLanguage: 'English', targetLanguage: 'French' } },
  ],
  tm: [
    { label: 'Software UI Strings', data: { sourceText: 'Save your changes before closing.\nAre you sure you want to delete this item?\nYour session has expired. Please log in again.\nFile uploaded successfully.\nNo results found for your search.', previousTranslations: 'Save changes = Cambios guardados\nDelete item = Eliminar elemento\nSession expired = Sesión expirada\nUpload successful = Carga exitosa', sourceLanguage: 'English', targetLanguage: 'Spanish' } },
    { label: 'Legal Disclaimer', data: { sourceText: 'This document contains confidential information. Unauthorized disclosure is strictly prohibited. All rights reserved under international copyright law.', previousTranslations: 'Confidential information = Informations confidentielles\nAll rights reserved = Tous droits réservés\nUnauthorized = Non autorisé', sourceLanguage: 'English', targetLanguage: 'French' } },
    { label: 'Product Description', data: { sourceText: 'Our premium wireless headphones feature active noise cancellation and 30-hour battery life. Available in black, white, and navy blue. Includes carrying case and USB-C charging cable.', previousTranslations: 'wireless headphones = kabellose Kopfhörer\nnoise cancellation = Geräuschunterdrückung\nbattery life = Akkulaufzeit\ncharging cable = Ladekabel', sourceLanguage: 'English', targetLanguage: 'German' } },
  ],
  quality: [
    { label: 'Technical Manual EN-ES', data: { sourceText: 'Before performing maintenance, ensure the machine is powered off and the lockout/tagout procedure has been followed. Disconnect all energy sources and verify zero energy state using a calibrated multimeter.', translatedText: 'Antes de realizar el mantenimiento, asegúrese de que la máquina esté apagada y se haya seguido el procedimiento de bloqueo/etiquetado. Desconecte todas las fuentes de energía y verifique el estado de energía cero utilizando un multímetro calibrado.', sourceLanguage: 'English', targetLanguage: 'Spanish', qualityFramework: 'MQM' } },
    { label: 'Marketing EN-FR (with issues)', data: { sourceText: 'Join thousands of happy customers who have transformed their morning routine with our organic cold-brew coffee. Taste the difference that ethically sourced beans make.', translatedText: 'Rejoignez des milliers de clients contents qui ont transformé leur routine du matin avec notre café infusé à froid biologique. Goûtez la différence que font les grains sourcés éthiquement.', sourceLanguage: 'English', targetLanguage: 'French', qualityFramework: 'MQM' } },
    { label: 'Legal EN-DE', data: { sourceText: 'The licensee shall not sublicense, transfer, or assign any rights granted under this agreement without the prior written consent of the licensor.', translatedText: 'Der Lizenznehmer darf keine unter dieser Vereinbarung gewährten Rechte unterlizenzieren, übertragen oder abtreten, ohne die vorherige schriftliche Zustimmung des Lizenzgebers.', sourceLanguage: 'English', targetLanguage: 'German', qualityFramework: 'MQM' } },
  ],
  cultural: [
    { label: 'US Ad for Japan Market', data: { text: 'Be the BEST version of yourself! Our self-improvement course will make YOU a winner. Stand out from the crowd! Individual success starts here. Use coupon code WINNER2026 for 40% off. The early bird gets the worm!', sourceculture: 'US/Western', targetCulture: 'Japanese', contentType: 'advertising' } },
    { label: 'Food Brand for Middle East', data: { text: 'Celebrate the holidays with our signature ham and wine gift basket! Perfect for Christmas dinner parties. Our premium pork sausages pair beautifully with a glass of our award-winning Cabernet Sauvignon. Makes a great stocking stuffer!', sourceculture: 'US/Western', targetCulture: 'Saudi Arabian/Gulf', contentType: 'product marketing' } },
    { label: 'Tech Brand for India', data: { text: 'Our new leather laptop bag comes in genuine cowhide. Perfect for the modern professional. Available in stores nationwide starting Black Friday. Dogs featured in our ad campaign represent loyalty to our brand.', sourceculture: 'US/Western', targetCulture: 'Indian', contentType: 'product marketing' } },
  ],
  seo: [
    { label: 'SaaS Landing Page', data: { text: 'The best project management software for remote teams. Streamline your workflow with AI-powered task automation, real-time collaboration, and advanced analytics. Start your free 14-day trial today.', keywords: 'project management, remote teams, task automation, collaboration tool', sourceLanguage: 'English', targetLanguage: 'Spanish', targetMarket: 'Spain' } },
    { label: 'E-commerce Category Page', data: { text: 'Shop our collection of sustainable fashion. Eco-friendly clothing made from organic cotton and recycled materials. Free returns within 30 days. Ethical fashion that looks good and does good.', keywords: 'sustainable fashion, eco-friendly clothing, organic cotton', sourceLanguage: 'English', targetLanguage: 'German', targetMarket: 'Germany' } },
    { label: 'Travel Blog Post', data: { text: 'Top 10 hidden gems in Southeast Asia. From pristine beaches in Vietnam to ancient temples in Myanmar. Budget-friendly travel tips for backpackers and digital nomads. Best time to visit: November to March.', keywords: 'Southeast Asia travel, hidden gems, budget travel, backpacking', sourceLanguage: 'English', targetLanguage: 'Japanese', targetMarket: 'Japan' } },
  ],
  backTranslation: [
    { label: 'Medical Consent Form', data: { sourceText: 'I understand that the proposed surgical procedure carries risks including infection, bleeding, and adverse reactions to anesthesia. I have been informed of alternative treatment options and have had the opportunity to ask questions.', translatedText: 'Comprendo que el procedimiento quirúrgico propuesto conlleva riesgos que incluyen infección, sangrado y reacciones adversas a la anestesia. He sido informado de las opciones de tratamiento alternativas y he tenido la oportunidad de hacer preguntas.', sourceLanguage: 'English', targetLanguage: 'Spanish', domain: 'medical' } },
    { label: 'Patent Claims', data: { sourceText: 'A method for processing natural language input comprising: receiving a text string; tokenizing said text string into a plurality of tokens; applying a transformer-based neural network to generate contextual embeddings.', translatedText: 'Ein Verfahren zur Verarbeitung natürlichsprachlicher Eingaben, umfassend: Empfangen einer Textzeichenfolge; Tokenisieren der genannten Textzeichenfolge in eine Vielzahl von Token; Anwenden eines transformerbasierten neuronalen Netzwerks zur Erzeugung kontextueller Einbettungen.', sourceLanguage: 'English', targetLanguage: 'German', domain: 'patent/legal' } },
    { label: 'Marketing Slogan', data: { sourceText: 'Think different. Just do it. Because you\'re worth it. The ultimate driving machine. Impossible is nothing.', translatedText: 'Pense diferente. Simplesmente faça. Porque você vale muito. A máquina de dirigir definitiva. Impossível não é nada.', sourceLanguage: 'English', targetLanguage: 'Portuguese', domain: 'marketing' } },
  ],
  sentiment: [
    { label: 'Customer Review', data: { sourceText: 'I absolutely love this product! It exceeded all my expectations. The quality is outstanding and the customer service team was incredibly helpful when I had questions. Highly recommend to everyone!', translatedText: 'Me gusta este producto. Cumplió con mis expectativas. La calidad es buena y el equipo de servicio al cliente fue útil cuando tuve preguntas. Lo recomiendo.', sourceLanguage: 'English', targetLanguage: 'Spanish' } },
    { label: 'Negative Feedback', data: { sourceText: 'This is the worst experience I have ever had. The product broke after one day and nobody from support responded to my emails. I am extremely frustrated and disappointed. I want a full refund immediately.', translatedText: 'C\'est la pire expérience que j\'ai jamais eue. Le produit s\'est cassé après un jour et personne du support n\'a répondu à mes e-mails. Je suis très mécontent. Je veux un remboursement.', sourceLanguage: 'English', targetLanguage: 'French' } },
    { label: 'Formal Press Release', data: { sourceText: 'We are pleased to announce our strategic partnership with GlobalTech Inc. This collaboration represents a significant milestone in our company\'s growth trajectory and will create substantial value for our shareholders and stakeholders.', sourceLanguage: 'English', targetLanguage: '' } },
  ],
  langDetect: [
    { label: 'Mixed Language Text', data: { text: 'Das ist wirklich eine interessante Frage. However, I think we should also consider the Japanese perspective: この問題は複雑です。Nous devons trouver une solution ensemble.', detectDialect: 'yes' } },
    { label: 'Regional Dialect', data: { text: 'Che boludo, ¿viste lo que pasó ayer en la cancha? El pibe la rompió toda, metió un golazo de media cancha. Después fuimos al asado y la pasamos re bien con los pibes del barrio.', detectDialect: 'yes' } },
    { label: 'Technical Text', data: { text: '본 연구에서는 딥러닝 기반의 자연어 처리 모델을 활용하여 한국어 감성 분석의 정확도를 향상시키는 방법을 제안합니다. 실험 결과, 제안된 모델이 기존 방법 대비 15% 높은 F1 스코어를 달성했습니다.', detectDialect: 'yes' } },
  ],
  readability: [
    { label: 'Complex Legal Text', data: { text: 'Notwithstanding any provisions to the contrary contained herein, the indemnifying party shall, upon receipt of written notification from the indemnified party of the existence of a claim, undertake at its sole cost and expense, the defense of such claim, provided however, that the indemnified party shall have the right to participate in such defense at its own expense through counsel of its own choosing.', language: 'English', targetAudience: 'general public', targetReadingLevel: '8th grade' } },
    { label: 'Medical Patient Guide', data: { text: 'Your doctor has prescribed metformin hydrochloride for the management of type 2 diabetes mellitus. This medication works by decreasing hepatic glucose production and improving insulin sensitivity in peripheral tissues. Take one 500mg tablet twice daily with meals. Common adverse effects include gastrointestinal disturbances such as nausea, diarrhea, and abdominal discomfort.', language: 'English', targetAudience: 'patients', targetReadingLevel: '6th grade' } },
    { label: 'Children\'s Science', data: { text: 'Photosynthesis is the biochemical process by which chloroplasts in plant cells convert electromagnetic radiation in the visible spectrum into chemical energy stored in glucose molecules through a series of light-dependent and light-independent reactions involving electron transport chains and carbon fixation via the Calvin cycle.', language: 'English', targetAudience: 'children ages 8-12', targetReadingLevel: '4th grade' } },
  ],
  styleTransfer: [
    { label: 'Academic to Casual Blog', data: { text: 'The empirical evidence suggests a statistically significant correlation between regular physical exercise and improved cognitive function in elderly populations. Furthermore, longitudinal studies indicate that aerobic activity of moderate intensity, performed three to five times weekly, may attenuate age-related cognitive decline.', sourceStyle: 'academic/scientific', targetStyle: 'casual blog post', language: 'English' } },
    { label: 'Formal to Social Media', data: { text: 'We are delighted to inform our valued clientele that our organization has successfully completed the acquisition of TechStart Inc., thereby expanding our portfolio of innovative solutions. This strategic initiative underscores our unwavering commitment to delivering excellence.', sourceStyle: 'formal corporate', targetStyle: 'fun social media post', language: 'English' } },
    { label: 'Technical to Marketing', data: { text: 'The device features a 6.7-inch AMOLED display with 120Hz refresh rate, 12GB LPDDR5 RAM, 256GB UFS 3.1 storage, a 50MP main camera with OIS and f/1.8 aperture, and a 5000mAh battery supporting 65W fast charging via USB-C PD 3.0.', sourceStyle: 'technical specifications', targetStyle: 'exciting marketing copy', language: 'English' } },
  ],
  summarize: [
    { label: 'Research Paper Abstract', data: { text: 'This paper investigates the impact of artificial intelligence on the translation industry over the past decade. We conducted a comprehensive survey of 500 professional translators across 30 countries and analyzed market data from 2015 to 2025. Our findings reveal that while AI-assisted translation tools have increased productivity by an average of 40%, they have not replaced human translators. Instead, the role has evolved toward post-editing, quality assurance, and cultural consulting. The market size has actually grown from $40 billion to $75 billion during this period. However, rates for straightforward translation work have decreased by 15-25%, while specialized services command premium pricing. We conclude that the translation industry is undergoing a fundamental transformation rather than disruption, with opportunities for professionals who adapt to the changing landscape.', targetLength: '3 sentences', language: 'English', summaryType: 'executive', focusAreas: 'market impact, translator roles' } },
    { label: 'Legal Contract Summary', data: { text: 'This Master Services Agreement is entered into as of January 1, 2026, between TranslateCo LLC and GlobalRetail Inc. The agreement covers translation services for product descriptions, marketing materials, and customer support content in 12 languages. The term is 24 months with automatic renewal. Pricing is $0.12 per word for standard translation, $0.18 for certified translation, and $0.08 for machine translation post-editing. Monthly minimum commitment is $15,000. Payment terms are Net 30. Confidentiality obligations survive 5 years after termination. Liability is capped at 12 months of fees paid. Governing law is State of New York.', targetLength: 'bullet points', language: 'English', summaryType: 'bullet points', focusAreas: 'pricing, terms, obligations' } },
    { label: 'News Article', data: { text: 'The European Union announced today a new regulation requiring all digital products sold within the EU to provide user interfaces in all 24 official languages by 2028. The regulation, known as the Digital Language Equality Act, also mandates that AI-generated translations must meet a minimum quality score of 85 on the MQM framework. Companies failing to comply face fines of up to 4% of annual global revenue. The regulation is expected to create an estimated 50,000 new jobs in the translation and localization industry. Industry groups have expressed both support and concern, with the European Federation of Translation noting that while the regulation validates the profession, the timeline may be challenging for smaller companies.', targetLength: '1 paragraph', language: 'English', summaryType: 'news summary', focusAreas: 'regulation details, industry impact' } },
  ],
  brandVoice: [
    { label: 'Startup Tech Brand', data: { text: 'We hereby inform you that our application has been updated with new functionality. Users are advised to download the latest version at their earliest convenience. The new features include improved performance metrics and enhanced security protocols.', brandGuidelines: 'Brand voice: Friendly, approachable, slightly playful. Use casual language, contractions, and direct address. Avoid jargon and corporate speak. Our personality is like a helpful friend who happens to be a tech expert. We use humor when appropriate.', language: 'English', contentType: 'app update notification', brandExamples: 'Hey there! We just dropped some awesome new features. Your app is about to get a whole lot faster.' } },
    { label: 'Luxury Fashion Brand', data: { text: 'Check out our cool new bags! They are really nice and made from good leather. Buy now and get free shipping. These bags are popular and selling fast so hurry up!', brandGuidelines: 'Brand voice: Elegant, sophisticated, understated luxury. Use refined language, evocative descriptions. Never use exclamation marks or urgent sales language. Our tone is confident, exclusive, and aspirational. Think Hermès or Bottega Veneta.', language: 'English', contentType: 'product announcement', brandExamples: 'Introducing the Maison collection - where timeless craftsmanship meets contemporary design. Each piece is meticulously handcrafted from the finest Italian leather.' } },
    { label: 'Healthcare Provider', data: { text: 'Yo, feeling sick? Pop into our clinic any time. We got docs who can fix you up real quick. No appointment needed, just walk in and we will sort you out. Easy peasy!', brandGuidelines: 'Brand voice: Warm, reassuring, professional yet accessible. Use clear, simple language that patients can understand. Avoid overly casual slang but also avoid intimidating medical jargon. Show empathy and competence. Comply with healthcare communication standards.', language: 'English', contentType: 'patient communication' } },
  ],
  subtitles: [
    { label: 'Movie Dialogue Scene', data: { text: 'Detective Miller enters the dimly lit room and approaches the suspect.\nMILLER: I know what you did last Thursday, and I have the evidence to prove it.\nSUSPECT: You have nothing. My lawyer will have this thrown out before lunch.\nMILLER: Your lawyer? He is the one who gave us the security footage. Turns out loyalty has a price.\nSUSPECT: (long pause) What do you want?\nMILLER: The truth. All of it. Starting with who hired you.', sourceLanguage: 'English', targetLanguage: 'Spanish', format: 'SRT', maxCharsPerLine: '42', maxLinesPerSubtitle: '2' } },
    { label: 'Corporate Training Video', data: { text: 'Welcome to the annual compliance training module. In this section, we will cover data privacy regulations including GDPR and CCPA. All employees must complete this training by December 31st. Please pay special attention to the sections on data handling and breach reporting procedures. Your completion certificate will be emailed automatically.', sourceLanguage: 'English', targetLanguage: 'French', format: 'VTT', maxCharsPerLine: '40', maxLinesPerSubtitle: '2' } },
    { label: 'Cooking Show', data: { text: 'Today we are making a classic Italian risotto. First, heat the olive oil in a heavy-bottomed pan. Add the finely diced onion and cook until translucent, about three minutes. Now add the Arborio rice and toast it for one minute, stirring constantly. Slowly add the warm chicken stock, one ladle at a time, stirring continuously. This process takes about 18 minutes.', sourceLanguage: 'English', targetLanguage: 'Japanese', format: 'SRT', maxCharsPerLine: '38', maxLinesPerSubtitle: '2' } },
  ],
  docCompare: [
    { label: 'Product Description EN-DE', data: { sourceText: 'Our wireless headphones feature:\n- Active noise cancellation\n- 30-hour battery life\n- Bluetooth 5.3 connectivity\n- Premium memory foam ear cushions\n- IPX4 water resistance\n- Built-in microphone with AI noise reduction\n\nAvailable in Midnight Black, Arctic White, and Ocean Blue.', translatedText: 'Unsere kabellosen Kopfhörer bieten:\n- Aktive Geräuschunterdrückung\n- 30 Stunden Akkulaufzeit\n- Bluetooth 5.3\n- Premium Memory-Schaum Ohrpolster\n- Wasserbeständigkeit\n\nErhältlich in Mitternachtsschwarz und Arktisches Weiß.', sourceLanguage: 'English', targetLanguage: 'German', comparisonType: 'full' } },
    { label: 'Legal Terms EN-FR', data: { sourceText: 'Terms of Service\n1. Acceptance of Terms\nBy using our service, you agree to these terms.\n2. Privacy Policy\nWe collect and process data as described in our Privacy Policy.\n3. Limitation of Liability\nOur total liability shall not exceed the amount paid in the preceding 12 months.\n4. Governing Law\nThis agreement is governed by the laws of the State of California.', translatedText: 'Conditions d\'Utilisation\n1. Acceptation des Conditions\nEn utilisant notre service, vous acceptez ces conditions.\n2. Politique de Confidentialité\nNous collectons et traitons les données comme décrit dans notre Politique de Confidentialité.\n3. Limitation de Responsabilité\nNotre responsabilité totale ne dépassera pas le montant payé au cours des 12 mois précédents.', sourceLanguage: 'English', targetLanguage: 'French', comparisonType: 'structural' } },
  ],
  competitor: [
    { label: 'SaaS Product Page', data: { yourContent: 'TranslateNow - Professional Translation Services\nWe offer translation in 50+ languages with 48-hour turnaround. Our team of certified translators ensures accuracy. Starting at $0.10/word.', competitorContent: 'LinguaGlobal - AI-Powered Translation Excellence\nInstant translations in 100+ languages with 99.5% accuracy. Real-time collaboration, translation memory, and brand consistency tools included. Trusted by Fortune 500 companies. Plans from $0.08/word with volume discounts.', language: 'English', market: 'US', industry: 'translation services' } },
    { label: 'App Store Description', data: { yourContent: 'LearnLang - Language Learning App\nLearn new languages with our app. Practice speaking, listening, reading. Available in 20 languages. Download free today.', competitorContent: 'FluentAI - Learn Languages Like a Native\n15 minutes a day is all you need! Our AI tutor adapts to YOUR learning style. Speech recognition scores your pronunciation in real-time. 40+ languages, offline mode, and learning streaks keep you motivated. 4.8 stars, 10M+ downloads. Start your journey today!', language: 'English', market: 'Global', industry: 'EdTech' } },
  ],
  projectAnalyzer: [
    { label: 'Website Localization Project', data: { projectDescription: 'Complete website localization for an e-commerce platform. Includes product descriptions (5,000 SKUs), checkout flow, customer support pages, legal pages (terms, privacy), marketing landing pages, and email templates. Content includes technical specs, marketing copy, and legal text.', sourceLanguage: 'English', targetLanguages: 'Spanish, French, German, Japanese, Chinese', wordCount: '250000', contentType: 'mixed (marketing, technical, legal)', deadline: '2026-08-01', budget: '$50,000' } },
    { label: 'Medical Document Translation', data: { projectDescription: 'Translation of clinical trial documentation for FDA submission. Includes protocol, informed consent forms, patient diaries, adverse event reports, and clinical study reports. All documents require certified translation with full audit trail.', sourceLanguage: 'English', targetLanguages: 'Spanish, Portuguese, Japanese', wordCount: '180000', contentType: 'medical/pharmaceutical', deadline: '2026-06-30', budget: '$80,000' } },
    { label: 'Game Localization', data: { projectDescription: 'Full localization of an open-world RPG game. Includes 200,000 words of dialogue, UI strings (8,000 strings), item descriptions (3,000 items), quest text, tutorial content, and marketing materials. Voice acting scripts for 50 characters.', sourceLanguage: 'Japanese', targetLanguages: 'English, Chinese, Korean, German, French, Spanish', wordCount: '350000', contentType: 'gaming/entertainment', deadline: '2026-12-01', budget: '$150,000' } },
  ],
  clientInsights: [
    { label: 'Enterprise Tech Client', data: { clientProfile: 'TechCorp Inc. - Enterprise software company, 5000+ employees, headquartered in San Francisco. Client since 2023. Industry: Technology/SaaS. Annual translation spend: $45,000. Primary languages: Japanese, Chinese, Korean, German.', projectHistory: 'Q1 2025: Website localization ($15k), Q2 2025: Product documentation ($12k), Q3 2025: Marketing campaign ($8k), Q4 2025: App localization ($10k). Quality ratings all above 4.5/5. On-time delivery: 95%.', communicationSamples: 'Recent email: "We are expanding to Southeast Asian markets next year. Can you handle Thai and Vietnamese? Also, we are interested in AI post-editing to reduce costs on our documentation updates."', industry: 'technology' } },
    { label: 'Pharmaceutical Client', data: { clientProfile: 'PharmaPlus AG - German pharmaceutical company, 12000 employees. Client since 2024. Industry: Pharmaceutical. Annual spend: $42,000. Requires certified translations. Primary languages: English, French, Spanish, Japanese.', projectHistory: 'Two projects completed: Drug labeling ($20k) - 2 weeks late, Clinical trial docs ($22k) - on time. Quality feedback: labeling had terminology issues flagged by regulatory.', communicationSamples: 'Last message: "We need faster turnaround on regulatory documents. The labeling terminology errors caused a submission delay. We are evaluating other agencies."', industry: 'pharmaceutical' } },
  ],
  translatorMatcher: [
    { label: 'Urgent Legal Project', data: { projectRequirements: 'Urgent translation of 50-page legal contract (15,000 words) from English to German. Requires knowledge of international commercial law, M&A terminology, and EU regulations. Must be completed within 5 business days. Certified translation required.', sourceLanguage: 'English', targetLanguage: 'German', domain: 'legal', availableTranslators: '1. Klaus Weber - German, Legal/Engineering specialist, $0.16/word, 4.7 rating, 11 years exp, available\n2. Hana Novak - Czech/German, IT/Automotive, $0.09/word, 4.7 rating, 7 years exp, available\n3. Ewa Kowalska - Polish/German, Medical/Pharma, $0.10/word, 4.8 rating, busy until next week', deadline: '2026-04-18', qualityTier: 'premium' } },
    { label: 'Gaming Localization Team', data: { projectRequirements: 'JRPG game localization - 80,000 words of dialogue, fantasy genre with humor. Need translator who understands gaming culture, anime references, and can adapt Japanese wordplay. Creative translation required, not literal.', sourceLanguage: 'Japanese', targetLanguage: 'English', domain: 'gaming/entertainment', availableTranslators: '1. Kenji Yamamoto - JP/EN/KR, Tech/Gaming, $0.15/word, 4.85 rating, 8 years, available\n2. Kim Soo-yeon - KR/EN/JP, Entertainment/Media, $0.13/word, 4.85 rating, 7 years, available\n3. Yuki Mori - Game Studio Tokyo client contact, unavailable', deadline: '2026-07-15', qualityTier: 'premium' } },
  ],
  glossaryGen: [
    { label: 'Fintech Product Docs', data: { referenceText: 'Our payment gateway supports tokenization of credit card data using PCI DSS compliant encryption. The checkout SDK integrates with your shopping cart via REST API webhooks. Merchants can configure recurring billing with subscription management, including dunning for failed payments. Our fraud detection engine uses machine learning to score transactions in real-time, flagging suspicious chargebacks and implementing 3D Secure authentication when the risk score exceeds the configured threshold.', sourceLanguage: 'English', targetLanguage: 'Spanish', domain: 'fintech/payments', existingTerms: 'API, SDK' } },
    { label: 'Climate Science Report', data: { referenceText: 'The Intergovernmental Panel on Climate Change reports that anthropogenic greenhouse gas emissions have reached unprecedented levels. The global carbon budget for limiting warming to 1.5°C is rapidly depleting. Key mitigation strategies include carbon capture and storage, renewable energy transition, reforestation, and methane reduction from agriculture. Climate adaptation measures such as sea-level rise barriers, drought-resistant crops, and urban heat island mitigation are increasingly critical.', sourceLanguage: 'English', targetLanguage: 'French', domain: 'climate science/environment', existingTerms: '' } },
  ],
  orderOptimizer: [
    { label: 'Monthly Order Batch', data: { orders: 'Order 1: EN-ES, 15000 words, marketing, deadline Apr 25, high priority\nOrder 2: EN-ES, 8000 words, legal, deadline Apr 28, normal priority\nOrder 3: EN-FR, 12000 words, technical, deadline Apr 30, normal priority\nOrder 4: EN-DE, 20000 words, medical, deadline May 5, urgent priority\nOrder 5: EN-JP, 5000 words, marketing, deadline Apr 22, high priority\nOrder 6: EN-ES, 3000 words, UI strings, deadline Apr 20, urgent\nOrder 7: EN-FR, 18000 words, legal, deadline May 10, normal\nOrder 8: EN-DE, 7000 words, marketing, deadline May 1, low', availableResources: 'Maria Garcia: EN-ES, Legal/Medical, 3000 words/day, available now\nFrancoise Martin: EN-FR, Marketing, 2500 words/day, available Apr 22\nKlaus Weber: EN-DE, Engineering/Medical, 2000 words/day, available now\nKenji Yamamoto: EN-JP, Tech/Gaming, 2000 words/day, available now\nAna Costa: EN-ES, Marketing/Tourism, 2500 words/day, available now', constraints: 'Monthly budget: $8,000. No overtime on weekends. Prefer to batch same-language orders.' } },
    { label: 'Rush Week Planning', data: { orders: 'Order A: JP-EN, 30000 words, game dialogue, deadline May 1, high\nOrder B: JP-EN, 5000 words, app strings, deadline Apr 28, urgent\nOrder C: DE-EN, 10000 words, automotive manual, deadline Apr 30, normal\nOrder D: FR-EN, 8000 words, fashion catalog, deadline May 2, normal', availableResources: 'Kenji: JP-EN, 2500 words/day\nKlaus: DE-EN, 2000 words/day\nFrancoise: FR-EN, 2500 words/day', constraints: 'Quality cannot be compromised. Consider splitting large orders across translators.' } },
  ],
  invoiceAnalyzer: [
    { label: 'Q1 2026 Invoice Data', data: { invoiceData: 'INV-001: TechCorp, $8,164, Jan 15, PAID Jan 20\nINV-002: TechCorp, $6,804, Jan 20, PAID Feb 1\nINV-003: Sakura Electronics, $6,048, Feb 1, PAID Jan 25 (early)\nINV-004: LuxeMode, $1,036, Feb 15, UNPAID (60 days overdue)\nINV-005: LuxeMode, $950, Feb 15, UNPAID (60 days overdue)\nINV-006: GlobalMed, $11,664, Mar 1, PAID Mar 28\nINV-007: AutoWerk, $4,147, Mar 15, PAID Mar 10 (early)\nINV-008: DragonTech, $2,052, Mar 15, PAID Apr 1\nINV-009: Bollywood Studios, $1,663, Mar 30, UNPAID\nINV-010: Bella Vita, $1,069, Mar 30, UNPAID\nINV-011: FinServ, $6,566, Feb 5, OVERDUE (65 days)\nINV-012: Game Studio, $17,280, Mar 1, PAID Mar 15', period: 'Q1 2026', targetRevenue: '$75,000 per quarter', pricingModel: 'Per-word pricing: $0.08-$0.20 depending on language pair and domain' } },
    { label: 'Annual Revenue Review', data: { invoiceData: 'Jan: $22,000 (5 invoices)\nFeb: $18,500 (4 invoices)\nMar: $31,000 (7 invoices)\nApr: $28,000 (6 invoices)\nMay: $35,000 (8 invoices)\nJun: $27,000 (5 invoices)\nJul: $19,000 (4 invoices) - summer slowdown\nAug: $21,000 (4 invoices)\nSep: $33,000 (7 invoices)\nOct: $38,000 (9 invoices)\nNov: $42,000 (10 invoices)\nDec: $25,000 (5 invoices) - holiday slowdown\nTotal: $339,500, 74 invoices, 3 overdue (4%)', period: '2025 Annual', targetRevenue: '$400,000 for 2026', pricingModel: 'Mixed: 70% per-word, 20% project-based, 10% retainer' } },
  ],
  biasCheck: [
    { label: 'Job Posting', data: { text: 'We are looking for a young, energetic salesman to join our team. The ideal candidate is a strong man who can handle the physical demands of the warehouse. He should be a native English speaker with no disabilities that would prevent him from performing the job. We offer competitive pay for a guy who can hit the ground running.', language: 'English', targetAudience: 'global', guidelines: 'Follow EEOC guidelines and inclusive hiring practices' } },
    { label: 'Healthcare Content', data: { text: 'Patients should consult their doctor. He will determine the appropriate treatment plan. Elderly patients may have difficulty understanding complex instructions. Diabetic patients are often overweight due to poor lifestyle choices. Mental health issues are less common in men because they are emotionally stronger.', language: 'English', targetAudience: 'US patients', guidelines: 'AMA health equity guidelines, person-first language' } },
    { label: 'Product Description', data: { text: 'This premium face cream is designed for women who want to look younger. Our anti-aging formula targets wrinkles and age spots that make you look old. Available in skin tone shades: light, medium, and dark. Perfect for the modern housewife who wants to maintain her beauty.', language: 'English', targetAudience: 'global', guidelines: 'Inclusive beauty standards, age-positive, gender-neutral when possible' } },
  ],
};

export default samples;
